# Generated by Django 5.0.3 on 2024-07-13 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesperson', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('tax_registration_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Must end with 00003', regex='^.*00003$'), django.core.validators.MinLengthValidator(15)])),
                ('cr_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('primary_contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tax_id', models.CharField(choices=[('Tax ID 1', 'Tax ID 1'), ('Tax ID 2', 'Tax ID 2')], max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('arabic_name', models.CharField(max_length=100)),
                ('tax_registration_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be 10 digits', regex='^\\d{10}$')])),
                ('website', models.URLField()),
                ('payment_terms', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('Country 1', 'Country 1'), ('Country 2', 'Country 2')], max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('additional_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^\\d{4}$')])),
                ('unit_number', models.CharField(max_length=4, validators=[django.core.validators.MaxLengthValidator(4)])),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('additional_street', models.CharField(max_length=100)),
                ('building_number', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^\\d{4}$')])),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must be 5 digits', regex='^\\d{5}$')])),
            ],
        ),
    ]
