# Generated by Django 5.0.3 on 2024-07-13 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='building_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Must be 4 digits', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Country 1', 'Country 1'), ('Country 2', 'Country 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cr_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Must be 5 digits', regex='^\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(choices=[('Tax ID 1', 'Tax ID 1'), ('Tax ID 2', 'Tax ID 2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_registration_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Must end with 00003', regex='^.*00003$'), django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unit_number',
            field=models.CharField(max_length=4, validators=[django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
