# Generated by Django 5.0.3 on 2024-07-14 13:59

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branches',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('branch1', 'Branch 1'), ('branch2', 'Branch 2'), ('branch3', 'Branch 3')], default=1, max_length=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('city1', 'City 1'), ('city2', 'City 2'), ('city3', 'City 3'), ('city4', 'City 4')], max_length=100),
        ),
    ]
